#! /bin/sh
#
# change this to the directory you run your bot from:
botdir="/usr/home/tecnobrat/rubybot/trunk"

# change this to the name of your bot's script in that directory:
botscript="/usr/local/bin/ruby main.rb"

# change this to the name of your bot's pidfile (capitalization COUNTS)
pidfile="bot.pid"

########## you probably don't need to change anything below here ##########

cd $botdir

# is there a pid file?
if test -r $pidfile
then
  # there is a pid file -- is it current?
  botpid=`cat $pidfile`
  if `kill -CHLD $botpid >/dev/null 2>&1`
  then
    # it's still going -- back out quietly
    exit 0
  fi
  echo ""
  echo "Stale $pidfile file, erasing..."
  rm -f $pidfile
fi

  echo ""
  echo "Couldn't find bot '$botname' running, reloading..."
  echo ""
  $botscript
  exit 0

exit 0
 
