CREATE TABLE 'users' (
	'id' INTEGER PRIMARY KEY NOT NULL,
	'nickname' VARCHAR(255) DEFAULT NULL,
	'hostname' VARCHAR(255) DEFAULT NULL,
	'location' VARCHAR(255) DEFAULT NULL,
	'rupture' VARCHAR(255) DEFAULT NULL
);

