armory:
  help: "Armory link generator. The format for @armory is '@armory <us/eu> <realm name> <character name>'."
  regex: '^(us|eu|kr|cn) (.*) (.*)$'
  command: "ArmoryModule.armory_link"
  num_args: 3
char:  
  help: "Armory Character Stats displayer. The format for @char is '@char <us/eu> <realm name> <character name>'."
  regex: '^(us|eu|kr|cn) (.*) (.*)$'
  command: "ArmoryModule.char_info"
  num_args: 3
ap:
  help: "Arena point calculator. The format for @ap is '@ap <5/3/2> <points>'."
  regex: "^([235]) ([0-9]*)$"
  num_args: 2
  command: "ArmoryModule.show_points"
realmstatus:
  help: "Shows realm up/down status.  The format for @realmstatus is '@realmstatus <us/eu> [optional server name]'."
  regex: '^(us|eu)(.*)'
  command: "Wow.realmstatus"
  num_args: 1
greed:  
  help: "Armory Character Greed displayer. The format for @greed is '@greed <us/eu> <realm name> <character name>'."
  regex: '^(us|eu|kr|cn) (.*) (.*)$'
  command: "ArmoryModule.greed"
  num_args: 3
notices:  
  help: "Wow Breaking News Displayer The format for @notices is '@notices'."
  command: "Wow.notices"
