CREATE TABLE 'channels' (
	'id' INTEGER PRIMARY KEY NOT NULL,
	'name' VARCHAR(255) DEFAULT NULL,
	'password' VARCHAR(255) DEFAULT NULL,
	'rupture' INTEGER(1) NOT NULL DEFAULT 0,
	'youtube' INTEGER(1) NOT NULL DEFAULT 0
);

