CREATE TABLE 'users' (
	'id' INTEGER PRIMARY KEY NOT NULL,
	'nickname' VARCHAR(255) DEFAULT NULL,
	'password' VARCHAR(255) DEFAULT NULL,
	'location' VARCHAR(255) DEFAULT NULL,
	'admin' INTEGER DEFAULT 0
);

